"""initial v2.1 schema

Revision ID: ff58c6bc93c7
Revises:
Create Date: 2026-07-11 03:12:02.368199
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ff58c6bc93c7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("brief", sa.Text(), nullable=False),
        sa.Column("constraints", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "input_artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("filename", sa.String(length=500), nullable=True),
        sa.Column("mime_type", sa.String(length=200), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("storage_path", sa.Text(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("input_artifacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_input_artifacts_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "rejected_feedback",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("asset_candidate_id", sa.String(length=36), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("perceptual_hash", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "asset_candidate_id", name="uq_rejected_workspace_asset"
        ),
    )
    with op.batch_alter_table("rejected_feedback", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rejected_feedback_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "research_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("goal", sa.String(length=50), nullable=False),
        sa.Column("budget_mode", sa.String(length=20), nullable=False),
        sa.Column("budget", sa.JSON(), nullable=False),
        sa.Column("allowed_domains", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("checkpoint_stage", sa.String(length=30), nullable=True),
        sa.Column("coverage_report", sa.JSON(), nullable=False),
        sa.Column("stop_reason", sa.String(length=200), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("research_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_research_runs_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_research_runs_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "saved_references",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("asset_candidate_id", sa.String(length=36), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "asset_candidate_id", name="uq_saved_workspace_asset"),
    )
    with op.batch_alter_table("saved_references", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_saved_references_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "query_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("purpose", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["research_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("query_attempts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_query_attempts_run_id"), ["run_id"], unique=False)

    op.create_table(
        "reference_boards",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("selected_asset_ids", sa.JSON(), nullable=False),
        sa.Column("layout", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["research_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reference_boards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reference_boards_run_id"), ["run_id"], unique=True)

    op.create_table(
        "source_pages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("publisher", sa.String(length=300), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("publication_tier", sa.String(length=30), nullable=False),
        sa.Column("access_status", sa.String(length=30), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["research_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "url", name="uq_source_page_run_url"),
    )
    with op.batch_alter_table("source_pages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_pages_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_source_pages_run_id"), ["run_id"], unique=False)

    op.create_table(
        "trace_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("tool", sa.String(length=100), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["research_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "sequence", name="uq_trace_run_sequence"),
    )
    with op.batch_alter_table("trace_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trace_events_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_trace_events_stage"), ["stage"], unique=False)

    op.create_table(
        "asset_candidates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("source_page_id", sa.String(length=36), nullable=True),
        sa.Column("project_name", sa.String(length=500), nullable=False),
        sa.Column("asset_type", sa.String(length=100), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("storage_path", sa.Text(), nullable=True),
        sa.Column("perceptual_hash", sa.String(length=64), nullable=True),
        sa.Column("publication_tier", sa.String(length=30), nullable=False),
        sa.Column("project_identity", sa.String(length=30), nullable=False),
        sa.Column("asset_association", sa.String(length=30), nullable=False),
        sa.Column("primary_source", sa.String(length=30), nullable=False),
        sa.Column("rights_status", sa.String(length=30), nullable=False),
        sa.Column("result_tier", sa.String(length=30), nullable=False),
        sa.Column("relevance", sa.Integer(), nullable=False),
        sa.Column("facts", sa.JSON(), nullable=False),
        sa.Column("observations", sa.JSON(), nullable=False),
        sa.Column("inferences", sa.JSON(), nullable=False),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column("rank_index", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["research_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_page_id"], ["source_pages.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "source_url", "image_url", name="uq_asset_run_source_image"),
    )
    with op.batch_alter_table("asset_candidates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_asset_candidates_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_asset_candidates_perceptual_hash"), ["perceptual_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_asset_candidates_result_tier"), ["result_tier"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_asset_candidates_run_id"), ["run_id"], unique=False)
        batch_op.create_index("ix_asset_run_rank", ["run_id", "rank_index"], unique=False)

    op.create_table(
        "style_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("board_id", sa.String(length=36), nullable=False),
        sa.Column("palette", sa.JSON(), nullable=False),
        sa.Column("line_weights", sa.JSON(), nullable=False),
        sa.Column("texture", sa.String(length=200), nullable=False),
        sa.Column("font_category", sa.String(length=200), nullable=False),
        sa.Column("layout_notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["board_id"], ["reference_boards.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("style_profiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_style_profiles_board_id"), ["board_id"], unique=True)

    op.create_table(
        "evidence_claims",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("asset_candidate_id", sa.String(length=36), nullable=False),
        sa.Column("claim_type", sa.String(length=30), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("pdf_page", sa.Integer(), nullable=True),
        sa.Column("text_excerpt", sa.Text(), nullable=True),
        sa.Column("image_region", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_candidate_id"], ["asset_candidates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidence_claims", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evidence_claims_asset_candidate_id"),
            ["asset_candidate_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_evidence_claims_expires_at"), ["expires_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evidence_claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_claims_expires_at"))
        batch_op.drop_index(batch_op.f("ix_evidence_claims_asset_candidate_id"))

    op.drop_table("evidence_claims")
    with op.batch_alter_table("style_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_style_profiles_board_id"))

    op.drop_table("style_profiles")
    with op.batch_alter_table("asset_candidates", schema=None) as batch_op:
        batch_op.drop_index("ix_asset_run_rank")
        batch_op.drop_index(batch_op.f("ix_asset_candidates_run_id"))
        batch_op.drop_index(batch_op.f("ix_asset_candidates_result_tier"))
        batch_op.drop_index(batch_op.f("ix_asset_candidates_perceptual_hash"))
        batch_op.drop_index(batch_op.f("ix_asset_candidates_expires_at"))

    op.drop_table("asset_candidates")
    with op.batch_alter_table("trace_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trace_events_stage"))
        batch_op.drop_index(batch_op.f("ix_trace_events_run_id"))

    op.drop_table("trace_events")
    with op.batch_alter_table("source_pages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_pages_run_id"))
        batch_op.drop_index(batch_op.f("ix_source_pages_expires_at"))

    op.drop_table("source_pages")
    with op.batch_alter_table("reference_boards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reference_boards_run_id"))

    op.drop_table("reference_boards")
    with op.batch_alter_table("query_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_query_attempts_run_id"))

    op.drop_table("query_attempts")
    with op.batch_alter_table("saved_references", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saved_references_workspace_id"))

    op.drop_table("saved_references")
    with op.batch_alter_table("research_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_runs_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_research_runs_status"))

    op.drop_table("research_runs")
    with op.batch_alter_table("rejected_feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rejected_feedback_workspace_id"))

    op.drop_table("rejected_feedback")
    with op.batch_alter_table("input_artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_input_artifacts_workspace_id"))

    op.drop_table("input_artifacts")
    op.drop_table("workspaces")
    # ### end Alembic commands ###
